### ISSUE TITLE
[ENGINEERING] Implement Applications API functions.

### ISSUE THREAD

**Issue by kevinsun0904** [CSES-Open-Source/Opportune#48]
**What is the issue?**
A clear description of the task or feature to be implemented by the engineers. 
* Create a new file `applications.ts` in `frontend/src/api`. 
* Create `Application.ts` in `src/types` to store the types related to API calls. 
* Implement API function calls for Application in the frontend. These functions are the endpoints in the frontend that interact directly with the backend endpoints.

**Additional context**
Add any other context or screenshots about the enhancement here.
* For more information about what to send to the backend in the body, query and param, look at the backend documentation
* Feel free to reference the `users.ts` API functions that I have implemented

**Note**
* The JSON sent by the backend can only contain primitive types like strings, therefore the parser for company can be used to parse the dates for each `applicationStatus`.

**Comment by wwidjaja0** [comment]
So I'm a little confused on what you mean by "the parser for company can be used to parse the dates for each `applicationStatus`", would you mind elaborating?

(I know that when you try to make the type of status an empty array it's an error so I'm a little confused what I should exactly use/where I should go from here? Do you just simply mean just get the dates for each `applicationStatus` and that's it (if it exists?))

![image](https://github.com/user-attachments/assets/afbebca5-c806-40a7-a1cb-4ca4d8acf602)

**Comment by kevinsun0904** [comment]
> So I'm a little confused on what you mean by "the parser for company can be used to parse the dates for each `applicationStatus`", would you mind elaborating?
> 
> (I know that when you try to make the type of status an empty array it's an error so I'm a little confused what I should exactly use/where I should go from here? Do you just simply mean just get the dates for each `applicationStatus` and that's it (if it exists?))
> 
> ![image](https://private-user-images.githubusercontent.com/62527551/394062895-afbebca5-c806-40a7-a1cb-4ca4d8acf602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDkwNDUsIm5iZiI6MTczMzgwODc0NSwicGF0aCI6Ii82MjUyNzU1MS8zOTQwNjI4OTUtYWZiZWJjYTUtYzgwNi00MGE3LWExY2ItNGNhNGQ4YWNmNjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA1MzIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyODYwMGEyMmY3NGYyMjNhNGExYWZlOTVkODA3ODc5MmI2OGEyOGNmZWRjYzI1ZjcwMjY0YzBmZGZlNTAxZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xFV11LW7i6FOyvfI7IJqQy3QiqBS8scyuvfHvY_9frI)

What I mainly meant was that its sort of a safe check since when an application is returned as a json, any `Date` objects such as the date in application statuses would be returned as a string (I think ISO8601?), so it might be safer to parse it into a Date object explicitly after receiving the response. However thinking back now maybe this is entirely unnecessary? Feel free to leave this out for now.
